-- CreateEnum
CREATE TYPE "Role" AS ENUM ('MEMBER', 'ADMIN');

-- CreateEnum
CREATE TYPE "SnapshotStatus" AS ENUM ('ACTIVE', 'REPLACED');

-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('INBOUND', 'RETURN', 'ADJUSTMENT', 'PROMOTION', 'SOLD_OUT', 'OTHER');

-- CreateEnum
CREATE TYPE "EventChangeType" AS ENUM ('CREATE', 'UPDATE', 'DELETE');

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'MEMBER',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "warehouses" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "warehouses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skus" (
    "id" TEXT NOT NULL,
    "warehouseId" TEXT NOT NULL,
    "productCode" TEXT NOT NULL,
    "currentProductName" TEXT NOT NULL,
    "currentOption" TEXT,
    "currentBarcode" TEXT,
    "currentLocation" TEXT,
    "currentUnitCost" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "currentWarningQty" INTEGER NOT NULL DEFAULT 0,
    "currentDangerQty" INTEGER NOT NULL DEFAULT 0,
    "firstSeenDate" DATE NOT NULL,
    "lastSeenDate" DATE NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "skus_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "inventory_snapshots" (
    "id" TEXT NOT NULL,
    "warehouseId" TEXT NOT NULL,
    "snapshotDate" DATE NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "SnapshotStatus" NOT NULL DEFAULT 'ACTIVE',
    "sourceFileName" TEXT NOT NULL,
    "fileHash" TEXT NOT NULL,
    "rowCount" INTEGER NOT NULL,
    "isMock" BOOLEAN NOT NULL DEFAULT false,
    "uploadedById" TEXT NOT NULL,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "inventory_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "inventory_items" (
    "id" TEXT NOT NULL,
    "snapshotId" TEXT NOT NULL,
    "skuId" TEXT NOT NULL,
    "productCode" TEXT NOT NULL,
    "productName" TEXT NOT NULL,
    "option" TEXT,
    "barcode" TEXT,
    "location" TEXT,
    "category" TEXT,
    "unitCost" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "normalStock" INTEGER NOT NULL DEFAULT 0,
    "defectiveStock" INTEGER NOT NULL DEFAULT 0,
    "availableStock" INTEGER NOT NULL DEFAULT 0,
    "incomingStock" INTEGER NOT NULL DEFAULT 0,
    "warningQty" INTEGER NOT NULL DEFAULT 0,
    "dangerQty" INTEGER NOT NULL DEFAULT 0,
    "extra" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "inventory_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "inventory_events" (
    "id" TEXT NOT NULL,
    "warehouseId" TEXT NOT NULL,
    "skuId" TEXT,
    "eventType" "EventType" NOT NULL,
    "quantity" INTEGER,
    "note" TEXT NOT NULL,
    "eventDate" TIMESTAMP(3) NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "inventory_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event_histories" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "changeType" "EventChangeType" NOT NULL,
    "previousData" JSONB NOT NULL,
    "changedById" TEXT NOT NULL,
    "changedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "event_histories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "settings" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "stockoutSoonDays" INTEGER NOT NULL DEFAULT 7,
    "manageMaxDays" INTEGER NOT NULL DEFAULT 30,
    "overstockCoverageDays" INTEGER NOT NULL DEFAULT 90,
    "stagnantDays" INTEGER NOT NULL DEFAULT 30,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "settings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "warehouses_code_key" ON "warehouses"("code");

-- CreateIndex
CREATE INDEX "skus_warehouseId_idx" ON "skus"("warehouseId");

-- CreateIndex
CREATE UNIQUE INDEX "skus_warehouseId_productCode_key" ON "skus"("warehouseId", "productCode");

-- CreateIndex
CREATE INDEX "inventory_snapshots_warehouseId_snapshotDate_status_idx" ON "inventory_snapshots"("warehouseId", "snapshotDate", "status");

-- CreateIndex
CREATE UNIQUE INDEX "inventory_snapshots_warehouseId_snapshotDate_version_key" ON "inventory_snapshots"("warehouseId", "snapshotDate", "version");

-- CreateIndex
CREATE INDEX "inventory_items_skuId_idx" ON "inventory_items"("skuId");

-- CreateIndex
CREATE UNIQUE INDEX "inventory_items_snapshotId_skuId_key" ON "inventory_items"("snapshotId", "skuId");

-- CreateIndex
CREATE INDEX "inventory_events_warehouseId_eventDate_idx" ON "inventory_events"("warehouseId", "eventDate");

-- CreateIndex
CREATE INDEX "inventory_events_skuId_eventDate_idx" ON "inventory_events"("skuId", "eventDate");

-- AddForeignKey
ALTER TABLE "skus" ADD CONSTRAINT "skus_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_snapshots" ADD CONSTRAINT "inventory_snapshots_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_snapshots" ADD CONSTRAINT "inventory_snapshots_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_snapshotId_fkey" FOREIGN KEY ("snapshotId") REFERENCES "inventory_snapshots"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_skuId_fkey" FOREIGN KEY ("skuId") REFERENCES "skus"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_events" ADD CONSTRAINT "inventory_events_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_events" ADD CONSTRAINT "inventory_events_skuId_fkey" FOREIGN KEY ("skuId") REFERENCES "skus"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inventory_events" ADD CONSTRAINT "inventory_events_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event_histories" ADD CONSTRAINT "event_histories_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "inventory_events"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event_histories" ADD CONSTRAINT "event_histories_changedById_fkey" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
