'use client';

import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ReferenceDot, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { EventFormDialog } from '@/components/events/event-form-dialog';
import { buildDailyDeltas, sortObservations } from '@/domain/inventory/calculations';
import type { InventoryValueBreakdown, SkuAnalysis, StockObservation } from '@/domain/inventory/types';
import { formatCoverageDays, formatCurrency, formatNumber, formatSigned } from '@/lib/format';
import { formatKstDate, formatKstDateTime } from '@/lib/date';
import { riskBadgeVariant, riskLabel } from '@/lib/status';
import { eventTypeLabel } from '@/lib/event-types';
import type { SkuDescriptor } from '@/server/repositories/inventory-repository';

interface SkuDetailResponse {
  descriptor: SkuDescriptor;
  analysis: SkuAnalysis;
  valueBreakdown: InventoryValueBreakdown;
  observations: StockObservation[];
}

interface EventItem {
  id: string;
  eventType: string;
  quantity: number | null;
  note: string;
  eventDate: string;
  isAutoGenerated: boolean;
  createdBy: { name: string };
}

interface SkuDetailSheetProps {
  skuId: string | null;
  asOfDate: string;
  onOpenChange: (open: boolean) => void;
}

export function SkuDetailSheet({ skuId, asOfDate, onOpenChange }: SkuDetailSheetProps) {
  const [detail, setDetail] = useState<SkuDetailResponse | null>(null);
  const [events, setEvents] = useState<EventItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [rangeDays, setRangeDays] = useState<30 | 60 | 90>(30);
  const [formOpen, setFormOpen] = useState(false);
  const [formPrefill, setFormPrefill] = useState<{ quantity?: number; date?: string }>({});

  async function reload() {
    if (!skuId) return;
    setLoading(true);
    try {
      const [detailRes, eventsRes] = await Promise.all([
        fetch(`/api/sku/${skuId}?asOf=${asOfDate}`),
        fetch(`/api/events?skuId=${skuId}`),
      ]);
      if (detailRes.ok) setDetail(await detailRes.json());
      if (eventsRes.ok) {
        const body = await eventsRes.json();
        setEvents(body.events);
      }
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    if (skuId) reload();
    else {
      setDetail(null);
      setEvents([]);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [skuId, asOfDate]);

  const chartData = useMemo(() => {
    if (!detail) return [];
    const cutoff = new Date(asOfDate);
    cutoff.setDate(cutoff.getDate() - rangeDays);
    const cutoffStr = cutoff.toISOString().slice(0, 10);
    return detail.observations.filter((o) => o.date >= cutoffStr).map((o) => ({ date: o.date, availableStock: o.availableStock }));
  }, [detail, rangeDays, asOfDate]);

  const eventMarkers = useMemo(() => {
    if (chartData.length === 0) return [];
    const dates = new Set(chartData.map((d) => d.date));
    return events
      .filter((e) => dates.has(e.eventDate.slice(0, 10)))
      .map((e) => {
        const point = chartData.find((d) => d.date === e.eventDate.slice(0, 10));
        return point ? { date: e.eventDate.slice(0, 10), availableStock: point.availableStock, note: e.note, eventType: e.eventType } : null;
      })
      .filter((v): v is { date: string; availableStock: number; note: string; eventType: string } => v !== null);
  }, [chartData, events]);

  const unclassifiedIncreases = useMemo(() => {
    if (!detail) return [];
    const sorted = sortObservations(detail.observations);
    const deltas = buildDailyDeltas(sorted);
    return deltas
      .filter((d) => d.increase > 0)
      .filter((d) => !events.some((e) => e.eventDate.slice(0, 10) >= d.fromDate && e.eventDate.slice(0, 10) <= d.toDate))
      .slice(-3)
      .reverse();
  }, [detail, events]);

  async function handleDeleteEvent(id: string) {
    if (!confirm('이 이벤트를 삭제할까요? (이력은 보존됩니다)')) return;
    const res = await fetch(`/api/events/${id}`, { method: 'DELETE' });
    if (res.ok) {
      toast.success('삭제되었습니다.');
      reload();
    } else {
      toast.error('삭제에 실패했습니다.');
    }
  }

  return (
    <Sheet open={!!skuId} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full overflow-y-auto sm:max-w-2xl">
        {loading && !detail && (
          <div className="space-y-6 p-5">
            <div className="space-y-2">
              <Skeleton className="h-5 w-2/3" />
              <Skeleton className="h-4 w-1/3" />
            </div>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <div key={i} className="space-y-1.5">
                  <Skeleton className="h-3 w-16" />
                  <Skeleton className="h-4 w-20" />
                </div>
              ))}
            </div>
            <Skeleton className="h-56 w-full" />
            <div className="space-y-2">
              <Skeleton className="h-16 w-full" />
              <Skeleton className="h-16 w-full" />
            </div>
          </div>
        )}
        {detail && (
          <>
            <SheetHeader>
              <div className="flex items-center gap-2">
                <SheetTitle>{detail.descriptor.productName}</SheetTitle>
                <Badge variant={riskBadgeVariant(detail.analysis.thresholdRisk.level)}>{riskLabel(detail.analysis.thresholdRisk.level)}</Badge>
              </div>
              <SheetDescription>
                {detail.descriptor.productCode} · {detail.descriptor.warehouseName}
                {detail.descriptor.option ? ` · ${detail.descriptor.option}` : ''}
              </SheetDescription>
            </SheetHeader>

            <div className="space-y-6 p-5">
              {detail.analysis.tags.length > 0 && (
                <div className="flex flex-wrap gap-1.5">
                  {detail.analysis.tags.map((t) => (
                    <span key={t} className="rounded-md bg-muted px-2 py-0.5 text-xs text-muted-foreground">{t}</span>
                  ))}
                </div>
              )}

              <section>
                <h3 className="mb-2 text-sm font-semibold">현재 상태</h3>
                <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm sm:grid-cols-3">
                  <Field label="현재 가용재고" value={`${formatNumber(detail.analysis.latest.availableStock)}개`} />
                  <Field label="정상재고" value={`${formatNumber(detail.analysis.latest.normalStock)}개`} />
                  <Field label="불량재고" value={`${formatNumber(detail.analysis.latest.defectiveStock)}개`} />
                  <Field label="입고대기" value={`${formatNumber(detail.analysis.latest.incomingStock)}개`} />
                  <Field label="단위원가" value={formatCurrency(detail.analysis.latest.unitCost)} />
                  <Field label="재고자산 (정상재고 기준)" value={formatCurrency(detail.valueBreakdown.normalStockValue)} />
                </div>
                <div className="mt-2 grid grid-cols-3 gap-2 rounded-md bg-muted/40 p-2 text-xs text-muted-foreground">
                  <div>가용재고 금액: {formatCurrency(detail.valueBreakdown.availableStockValue)}</div>
                  <div>불량재고 금액: {formatCurrency(detail.valueBreakdown.defectiveStockValue)}</div>
                  <div>입고대기 금액: {formatCurrency(detail.valueBreakdown.incomingStockValue)}</div>
                </div>
              </section>

              <Separator />

              <section>
                <h3 className="mb-2 text-sm font-semibold">추세</h3>
                <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm sm:grid-cols-3">
                  <Field label="7일 평균 소진" value={fmtRate(detail.analysis.window7.averageDailyDepletion)} />
                  <Field label="14일 평균 소진" value={fmtRate(detail.analysis.window14.averageDailyDepletion)} />
                  <Field label="30일 평균 소진" value={fmtRate(detail.analysis.window30.averageDailyDepletion)} />
                  <Field label="소진 가속/둔화" value={accelerationText(detail.analysis)} />
                  <Field label="Coverage" value={formatCoverageDays(detail.analysis.coverage.coverageDays)} />
                  <Field
                    label="예상 소진일 (현재 추세 기준)"
                    value={
                      detail.analysis.forecast.expectedStockoutDate
                        ? `${formatKstDate(detail.analysis.forecast.expectedStockoutDate)} · 신뢰도 ${confidenceLabel(detail.analysis.forecast.confidence)}`
                        : '데이터 축적 중'
                    }
                  />
                </div>
              </section>

              <Separator />

              <section>
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="text-sm font-semibold">가용재고 추이</h3>
                  <Tabs value={String(rangeDays)} onValueChange={(v) => setRangeDays(Number(v) as 30 | 60 | 90)}>
                    <TabsList>
                      <TabsTrigger value="30">30일</TabsTrigger>
                      <TabsTrigger value="60">60일</TabsTrigger>
                      <TabsTrigger value="90">90일</TabsTrigger>
                    </TabsList>
                  </Tabs>
                </div>
                <div className="h-56">
                  {chartData.length < 2 ? (
                    <div className="flex h-full items-center justify-center text-sm text-muted-foreground">데이터 축적 중</div>
                  ) : (
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 0 }}>
                        <defs>
                          <linearGradient id="stockGradient" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="var(--color-chart-1)" stopOpacity={0.35} />
                            <stop offset="100%" stopColor="var(--color-chart-1)" stopOpacity={0} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid stroke="var(--color-border)" vertical={false} />
                        <XAxis dataKey="date" tickFormatter={(d: string) => formatKstDate(d).slice(5)} fontSize={11} stroke="var(--color-muted-foreground)" tickLine={false} axisLine={false} />
                        <YAxis width={44} fontSize={11} stroke="var(--color-muted-foreground)" tickLine={false} axisLine={false} />
                        <Tooltip labelFormatter={(d) => formatKstDate(String(d))} formatter={(v) => [`${Number(v).toLocaleString('ko-KR')}개`, '가용재고']} contentStyle={{ fontSize: 12, borderRadius: 8 }} />
                        <Area type="monotone" dataKey="availableStock" stroke="var(--color-chart-1)" fill="url(#stockGradient)" strokeWidth={2} />
                        {eventMarkers.map((m, i) => (
                          <ReferenceDot key={i} x={m.date} y={m.availableStock} r={4} fill="var(--color-chart-4)" stroke="var(--color-background)" />
                        ))}
                      </AreaChart>
                    </ResponsiveContainer>
                  )}
                </div>
              </section>

              {unclassifiedIncreases.length > 0 && (
                <div className="space-y-2 rounded-md border border-status-increase/30 bg-status-increase-bg p-3">
                  <div className="text-xs font-medium text-status-increase">재고 증가 감지 · 아직 분류되지 않았습니다</div>
                  {unclassifiedIncreases.map((d, i) => (
                    <div key={i} className="flex items-center justify-between text-xs">
                      <span>
                        {formatKstDate(d.toDate)} 기준 {formatSigned(d.increase)}개 증가
                      </span>
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-6 text-[11px]"
                        onClick={() => {
                          setFormPrefill({ quantity: d.increase, date: d.toDate });
                          setFormOpen(true);
                        }}
                      >
                        분류하기
                      </Button>
                    </div>
                  ))}
                </div>
              )}

              <Separator />

              <section>
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="text-sm font-semibold">메모 / 이벤트</h3>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setFormPrefill({});
                      setFormOpen(true);
                    }}
                  >
                    <Plus className="size-3.5" /> 추가
                  </Button>
                </div>
                <div className="space-y-2">
                  {events.length === 0 && <p className="text-sm text-muted-foreground">등록된 이벤트가 없습니다.</p>}
                  {events.map((e) => (
                    <div key={e.id} className="rounded-md border p-2.5 text-sm">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <Badge variant="outline">{eventTypeLabel(e.eventType)}</Badge>
                          {e.quantity !== null && <span className="text-xs text-muted-foreground">{formatSigned(e.quantity)}개</span>}
                        </div>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          {formatKstDateTime(e.eventDate)}
                          <button onClick={() => handleDeleteEvent(e.id)} className="text-muted-foreground hover:text-destructive" aria-label="삭제">
                            <Trash2 className="size-3.5" />
                          </button>
                        </div>
                      </div>
                      <p className="mt-1 text-sm">{e.note}</p>
                      <p className="mt-1 text-[11px] text-muted-foreground">작성자: {e.createdBy.name}</p>
                    </div>
                  ))}
                </div>
              </section>
            </div>

            <EventFormDialog
              open={formOpen}
              onOpenChange={setFormOpen}
              warehouseId={detail.descriptor.warehouseId}
              skuId={detail.descriptor.skuId}
              skuLabel={detail.descriptor.productName}
              defaultQuantity={formPrefill.quantity}
              defaultEventDate={formPrefill.date}
              onCreated={reload}
            />
          </>
        )}
      </SheetContent>
    </Sheet>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="font-medium tabular-nums">{value}</div>
    </div>
  );
}

function fmtRate(value: number | null): string {
  return value === null ? '데이터 축적 중' : `${formatNumber(value)}개/일`;
}

function accelerationText(analysis: SkuAnalysis): string {
  const { trend, accelerationRatePercent } = analysis.acceleration;
  if (trend === null) return '데이터 축적 중';
  if (trend === 'NEW_DEPLETION') return '신규 소진 발생';
  if (trend === 'ACCELERATING') return `🔥 소진 가속 (+${Math.round(accelerationRatePercent ?? 0)}%)`;
  if (trend === 'DECELERATING') return `↓ 소진 둔화 (${Math.round(accelerationRatePercent ?? 0)}%)`;
  return '안정적';
}

function confidenceLabel(confidence: SkuAnalysis['forecast']['confidence']): string {
  if (confidence === 'HIGH') return '높음';
  if (confidence === 'MEDIUM') return '보통';
  if (confidence === 'LOW') return '낮음';
  return '-';
}
