'use client';

import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ReferenceDot, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Building2, PackageX, Pencil, Plus, RotateCcw, Star, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { InfoTooltip } from '@/components/ui/info-tooltip';
import { EventFormDialog } from '@/components/events/event-form-dialog';
import { buildDailyDeltas, calculatePeriodComparison, sortObservations } from '@/domain/inventory/calculations';
import type { InventoryValueBreakdown, SkuAnalysis, StockObservation } from '@/domain/inventory/types';
import { formatCoverageDays, formatCurrency, formatNumber, formatSigned } from '@/lib/format';
import { formatKstDate, formatKstDateTime } from '@/lib/date';
import { riskBadgeVariant, riskLabel } from '@/lib/status';
import { eventTypeLabel } from '@/lib/event-types';
import type { SkuDescriptor } from '@/domain/inventory/read-model';

interface SkuDetailResponse {
  descriptor: SkuDescriptor;
  analysis: SkuAnalysis;
  valueBreakdown: InventoryValueBreakdown;
  observations: StockObservation[];
}

interface EventItem {
  id: string;
  eventType: string;
  quantity: number | null;
  note: string;
  eventDate: string;
  isAutoGenerated: boolean;
  createdBy: { name: string };
}

interface SkuDetailSheetProps {
  skuId: string | null;
  asOfDate: string;
  fromDate: string | null;
  isAdmin: boolean;
  isFavorited: boolean;
  onToggleFavorite: (skuId: string, next: boolean) => void;
  onOpenChange: (open: boolean) => void;
}

export function SkuDetailSheet({ skuId, asOfDate, fromDate, isAdmin, isFavorited, onToggleFavorite, onOpenChange }: SkuDetailSheetProps) {
  const [detail, setDetail] = useState<SkuDetailResponse | null>(null);
  const [events, setEvents] = useState<EventItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [rangeDays, setRangeDays] = useState<30 | 60 | 90>(30);
  const [formOpen, setFormOpen] = useState(false);
  const [formPrefill, setFormPrefill] = useState<{ quantity?: number; date?: string }>({});
  const [editingThresholds, setEditingThresholds] = useState(false);
  const [dangerInput, setDangerInput] = useState('');
  const [warningInput, setWarningInput] = useState('');
  const [savingThresholds, setSavingThresholds] = useState(false);
  const [togglingB2B, setTogglingB2B] = useState(false);

  async function reload() {
    if (!skuId) return;
    setLoading(true);
    try {
      const [detailRes, eventsRes] = await Promise.all([
        fetch(`/api/sku/${skuId}?asOf=${asOfDate}`),
        fetch(`/api/events?skuId=${skuId}`),
      ]);
      if (detailRes.ok) setDetail(await detailRes.json());
      if (eventsRes.ok) {
        const body = await eventsRes.json();
        setEvents(body.events);
      }
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (skuId) reload();
    else {
      setDetail(null);
      setEvents([]);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [skuId, asOfDate]);

  const chartData = useMemo(() => {
    if (!detail) return [];
    const cutoff = new Date(asOfDate);
    cutoff.setDate(cutoff.getDate() - rangeDays);
    const cutoffStr = fromDate ?? cutoff.toISOString().slice(0, 10);
    return detail.observations.filter((o) => o.date >= cutoffStr).map((o) => ({ date: o.date, availableStock: o.availableStock }));
  }, [detail, rangeDays, asOfDate, fromDate]);

  const periodMetrics = useMemo(() => {
    if (!detail || !fromDate) return null;
    return calculatePeriodComparison(detail.observations, fromDate, asOfDate);
  }, [detail, fromDate, asOfDate]);

  const eventMarkers = useMemo(() => {
    if (chartData.length === 0) return [];
    const dates = new Set(chartData.map((d) => d.date));
    return events
      .filter((e) => dates.has(formatKstDate(e.eventDate)))
      .map((e) => {
        const eventKstDate = formatKstDate(e.eventDate);
        const point = chartData.find((d) => d.date === eventKstDate);
        return point ? { date: eventKstDate, availableStock: point.availableStock, note: e.note, eventType: e.eventType } : null;
      })
      .filter((v): v is { date: string; availableStock: number; note: string; eventType: string } => v !== null);
  }, [chartData, events]);

  // 이 SKU에 관측치가 이번 한 건뿐이면(과거 이력 없음) 현재 표시된 재고는 처음 인식된 그대로의
  // 초기재고다 — 소진/증가 계산 대상이 아니므로 계산 로직은 이미 이를 건드리지 않고, 여기서는
  // 그 사실을 사용자에게 보이는 태그로만 알려준다.
  const isInitialObservation = useMemo(() => {
    if (!detail) return false;
    return sortObservations(detail.observations).length <= 1;
  }, [detail]);

  async function toggleB2B(checked: boolean) {
    if (!skuId) return;
    setTogglingB2B(true);
    try {
      const res = await fetch(`/api/sku/${skuId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isB2B: checked }),
      });
      if (!res.ok) throw new Error();
      toast.success(checked ? 'B2B 상품으로 표시했습니다.' : 'B2B 표시를 해제했습니다.');
      reload();
    } catch {
      toast.error('변경에 실패했습니다.');
    } finally {
      setTogglingB2B(false);
    }
  }

  const unclassifiedIncreases = useMemo(() => {
    if (!detail) return [];
    const sorted = sortObservations(detail.observations);
    const deltas = buildDailyDeltas(sorted);
    return deltas
      .filter((d) => d.increase > 0)
      .filter((d) => !events.some((e) => formatKstDate(e.eventDate) >= d.fromDate && formatKstDate(e.eventDate) <= d.toDate))
      .slice(-3)
      .reverse();
  }, [detail, events]);

  function startEditingThresholds() {
    if (!detail) return;
    setDangerInput(String(detail.analysis.riskThresholds.dangerQty));
    setWarningInput(String(detail.analysis.riskThresholds.warningQty));
    setEditingThresholds(true);
  }

  async function saveThresholds() {
    if (!skuId) return;
    const dangerQty = Number(dangerInput);
    const warningQty = Number(warningInput);
    if (!Number.isInteger(dangerQty) || dangerQty < 0 || !Number.isInteger(warningQty) || warningQty < 0) {
      toast.error('0 이상의 정수만 입력할 수 있습니다.');
      return;
    }
    setSavingThresholds(true);
    try {
      const res = await fetch(`/api/sku/${skuId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ manualDangerQty: dangerQty, manualWarningQty: warningQty }),
      });
      if (!res.ok) throw new Error();
      toast.success('위험/경고수량을 저장했습니다.');
      setEditingThresholds(false);
      reload();
    } catch {
      toast.error('저장에 실패했습니다.');
    } finally {
      setSavingThresholds(false);
    }
  }

  async function resetThresholds() {
    if (!skuId) return;
    setSavingThresholds(true);
    try {
      const res = await fetch(`/api/sku/${skuId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ manualDangerQty: null, manualWarningQty: null }),
      });
      if (!res.ok) throw new Error();
      toast.success('자동계산으로 되돌렸습니다.');
      setEditingThresholds(false);
      reload();
    } catch {
      toast.error('되돌리기에 실패했습니다.');
    } finally {
      setSavingThresholds(false);
    }
  }

  async function handleDeleteEvent(id: string) {
    if (!confirm('이 이벤트를 삭제할까요? (이력은 보존됩니다)')) return;
    const res = await fetch(`/api/events/${id}`, { method: 'DELETE' });
    if (res.ok) {
      toast.success('삭제되었습니다.');
      reload();
    } else {
      toast.error('삭제에 실패했습니다.');
    }
  }

  return (
    <Sheet open={!!skuId} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full overflow-y-auto sm:max-w-[520px]">
        {loading && !detail && (
          <div className="space-y-6 p-5">
            <div className="space-y-2">
              <Skeleton className="h-5 w-2/3" />
              <Skeleton className="h-4 w-1/3" />
            </div>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <div key={i} className="space-y-1.5">
                  <Skeleton className="h-3 w-16" />
                  <Skeleton className="h-4 w-20" />
                </div>
              ))}
            </div>
            <Skeleton className="h-56 w-full" />
            <div className="space-y-2">
              <Skeleton className="h-16 w-full" />
              <Skeleton className="h-16 w-full" />
            </div>
          </div>
        )}
        {detail && (
          <>
            <SheetHeader>
              <div className="flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={() => skuId && onToggleFavorite(skuId, !isFavorited)}
                  className="shrink-0 rounded-md p-1 text-muted-foreground transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  aria-label={isFavorited ? '즐겨찾기 해제' : '즐겨찾기 추가'}
                  aria-pressed={isFavorited}
                >
                  <Star className={isFavorited ? 'size-4 fill-amber-400 text-amber-400' : 'size-4'} aria-hidden="true" />
                </button>
                <SheetTitle>{detail.descriptor.productName}</SheetTitle>
                {detail.descriptor.isSoldOut && (
                  <>
                    <Badge variant="soldout" className="gap-1">
                      <PackageX className="size-3" aria-hidden="true" />
                      품절
                    </Badge>
                    <InfoTooltip>
                      최신 업로드 목록에 없어 품절로 인식됐습니다. 품절 인식일({formatKstDate(detail.descriptor.soldOutDetectedDate!)})로부터 1개월간 품절 시점까지의 마지막 데이터로 노출됩니다.
                    </InfoTooltip>
                  </>
                )}
                <Badge variant={riskBadgeVariant(detail.analysis.thresholdRisk.level)}>{riskLabel(detail.analysis.thresholdRisk.level)}</Badge>
                {detail.descriptor.isB2B && (
                  <>
                    <Badge variant="outline" className="gap-1">
                      <Building2 className="size-3" aria-hidden="true" />
                      B2B
                    </Badge>
                    <InfoTooltip>B2B 상품의 경우 KPI의 신뢰도가 낮을 수 있습니다.</InfoTooltip>
                  </>
                )}
              </div>
              <SheetDescription>
                {detail.descriptor.productCode} · {detail.descriptor.warehouseName}
                {detail.descriptor.option ? ` · ${detail.descriptor.option}` : ''}
                {' · 최초 인식 '}
                {formatKstDate(detail.descriptor.firstSeenDate)}
              </SheetDescription>
            </SheetHeader>

            <div className="space-y-5 p-4 sm:p-5">
              {(detail.analysis.tags.length > 0 || isInitialObservation) && (
                <div className="flex flex-wrap gap-1.5">
                  {isInitialObservation && (
                    <span className="rounded-md bg-status-increase-bg px-2 py-0.5 text-xs text-status-increase">[초기재고]</span>
                  )}
                  {detail.analysis.tags.map((t) => (
                    <span key={t} className="rounded-md bg-muted px-2 py-0.5 text-xs text-muted-foreground">{t}</span>
                  ))}
                </div>
              )}

              <section className="grid grid-cols-2 gap-2">
                <MetricCard label="가용재고" value={`${formatNumber(detail.analysis.latest.availableStock)}개`} />
                <MetricCard label="재고자산" value={formatCurrency(detail.valueBreakdown.normalStockValue)} />
                <MetricCard label="Coverage" value={formatCoverageDays(detail.analysis.coverage.coverageDays)} />
                <MetricCard
                  label="예상 소진일"
                  value={detail.analysis.forecast.expectedStockoutDate ? formatKstDate(detail.analysis.forecast.expectedStockoutDate) : '데이터 축적 중'}
                />
              </section>

              <section className="rounded-xl border bg-muted/30 p-3">
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="text-xs font-semibold">위험/경고수량 기준</h3>
                  {isAdmin && !editingThresholds && (
                    <Button variant="ghost" size="sm" className="h-6 px-2 text-[11px]" onClick={startEditingThresholds}>
                      <Pencil className="size-3" /> 수정
                    </Button>
                  )}
                </div>
                {editingThresholds ? (
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-xs">
                      <label htmlFor="danger-qty-input" className="w-16 text-muted-foreground">위험수량</label>
                      <Input id="danger-qty-input" value={dangerInput} onChange={(e) => setDangerInput(e.target.value)} inputMode="numeric" className="h-8 text-xs" />
                    </div>
                    <div className="flex items-center gap-2 text-xs">
                      <label htmlFor="warning-qty-input" className="w-16 text-muted-foreground">경고수량</label>
                      <Input id="warning-qty-input" value={warningInput} onChange={(e) => setWarningInput(e.target.value)} inputMode="numeric" className="h-8 text-xs" />
                    </div>
                    <div className="flex flex-wrap items-center gap-2 pt-1">
                      <Button size="sm" className="h-7 text-xs" onClick={saveThresholds} disabled={savingThresholds}>
                        저장
                      </Button>
                      <Button size="sm" variant="outline" className="h-7 text-xs" onClick={resetThresholds} disabled={savingThresholds}>
                        <RotateCcw className="size-3" /> 자동으로 되돌리기
                      </Button>
                      <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => setEditingThresholds(false)} disabled={savingThresholds}>
                        취소
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
                    <Field label="위험수량" value={`${formatNumber(detail.analysis.riskThresholds.dangerQty)}개`} />
                    <Field label="경고수량" value={`${formatNumber(detail.analysis.riskThresholds.warningQty)}개`} />
                  </div>
                )}
                {!editingThresholds && <p className="mt-2 text-[11px] text-muted-foreground">{thresholdSourceLabel(detail.analysis.riskThresholds.source)}</p>}
              </section>

              {isAdmin && (
                <section className="flex items-center justify-between rounded-xl border bg-muted/30 p-3">
                  <div className="flex items-center gap-1.5">
                    <Building2 className="size-3.5 text-muted-foreground" aria-hidden="true" />
                    <span className="text-xs font-semibold">B2B 상품</span>
                    <InfoTooltip>B2B 상품의 경우 KPI의 신뢰도가 낮을 수 있습니다.</InfoTooltip>
                  </div>
                  <Switch checked={detail.descriptor.isB2B} onCheckedChange={toggleB2B} disabled={togglingB2B} aria-label="B2B 상품 표시" />
                </section>
              )}

              {fromDate && (
                <section className="rounded-xl border bg-muted/30 p-3">
                  <div className="mb-3 flex items-center justify-between">
                    <h3 className="text-xs font-semibold">선택 기간 변화</h3>
                    <span className="text-[11px] text-muted-foreground">
                      {periodMetrics ? `${periodMetrics.actualStartDate.slice(5)} — ${periodMetrics.actualEndDate.slice(5)} 관측 기준` : `${fromDate.slice(5)} — ${asOfDate.slice(5)}`}
                    </span>
                  </div>
                  {periodMetrics ? (
                    <div className="grid grid-cols-2 gap-x-4 gap-y-3 text-sm">
                      <Field label="순 변화" value={`${formatSigned(periodMetrics.netChange)}개`} />
                      <Field label="관측 감소" value={`${formatNumber(periodMetrics.totalDepletion)}개`} />
                      <Field label="관측 증가" value={`${formatNumber(periodMetrics.totalIncrease)}개`} />
                      <Field label="입고 반영" value={`${formatNumber(periodMetrics.totalInboundQuantity ?? 0)}개`} />
                      <Field label="기간 일평균 소진" value={fmtRate(periodMetrics.averageDailyDepletion)} />
                    </div>
                  ) : <p className="text-xs text-muted-foreground">두 날짜를 비교할 관측 데이터가 부족합니다.</p>}
                </section>
              )}

              <Separator />

              <section>
                <h3 className="mb-2 text-sm font-semibold">추세</h3>
                <div className="grid grid-cols-2 gap-x-4 gap-y-3 text-sm">
                  <Field label="7일 평균 소진" value={fmtRate(detail.analysis.window7.averageDailyDepletion)} />
                  <Field label="7일 입고 반영" value={`${formatNumber(detail.analysis.window7.totalInboundQuantity ?? 0)}개`} />
                  <Field label="14일 평균 소진" value={fmtRate(detail.analysis.window14.averageDailyDepletion)} />
                  <Field label="30일 평균 소진" value={fmtRate(detail.analysis.window30.averageDailyDepletion)} />
                  <Field label="소진 가속/둔화" value={accelerationText(detail.analysis)} />
                  <Field label="관측 근거 수준" value={confidenceLabel(detail.analysis.forecast.confidence)} />
                </div>
              </section>

              <Separator />

              <section>
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="text-sm font-semibold">가용재고 추이</h3>
                  {!fromDate && <Tabs value={String(rangeDays)} onValueChange={(v) => setRangeDays(Number(v) as 30 | 60 | 90)}>
                    <TabsList>
                      <TabsTrigger value="30">30일</TabsTrigger>
                      <TabsTrigger value="60">60일</TabsTrigger>
                      <TabsTrigger value="90">90일</TabsTrigger>
                    </TabsList>
                  </Tabs>}
                </div>
                <div className="h-48">
                  {chartData.length < 2 ? (
                    <div className="flex h-full items-center justify-center text-sm text-muted-foreground">데이터 축적 중</div>
                  ) : (
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 0 }}>
                        <defs>
                          <linearGradient id="stockGradient" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="var(--color-chart-1)" stopOpacity={0.35} />
                            <stop offset="100%" stopColor="var(--color-chart-1)" stopOpacity={0} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid stroke="var(--color-border)" vertical={false} />
                        <XAxis dataKey="date" tickFormatter={(d: string) => formatKstDate(d).slice(5)} fontSize={11} stroke="var(--color-muted-foreground)" tickLine={false} axisLine={false} />
                        <YAxis width={44} fontSize={11} stroke="var(--color-muted-foreground)" tickLine={false} axisLine={false} />
                        <Tooltip labelFormatter={(d) => formatKstDate(String(d))} formatter={(v) => [`${Number(v).toLocaleString('ko-KR')}개`, '가용재고']} contentStyle={{ fontSize: 12, borderRadius: 8 }} />
                        <Area type="monotone" dataKey="availableStock" stroke="var(--color-chart-1)" fill="url(#stockGradient)" strokeWidth={2} />
                        {eventMarkers.map((m, i) => (
                          <ReferenceDot key={i} x={m.date} y={m.availableStock} r={4} fill="var(--color-chart-4)" stroke="var(--color-background)" />
                        ))}
                      </AreaChart>
                    </ResponsiveContainer>
                  )}
                </div>
              </section>

              {unclassifiedIncreases.length > 0 && (
                <div className="space-y-2 rounded-md border border-status-increase/30 bg-status-increase-bg p-3">
                  <div className="text-xs font-medium text-status-increase">재고 증가 감지 · 아직 분류되지 않았습니다</div>
                  {unclassifiedIncreases.map((d, i) => (
                    <div key={i} className="flex items-center justify-between text-xs">
                      <span>
                        {formatKstDate(d.toDate)} 기준 {formatSigned(d.increase)}개 증가
                      </span>
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-6 text-[11px]"
                        onClick={() => {
                          setFormPrefill({ quantity: d.increase, date: d.toDate });
                          setFormOpen(true);
                        }}
                      >
                        분류하기
                      </Button>
                    </div>
                  ))}
                </div>
              )}

              <Separator />

              <section>
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="text-sm font-semibold">메모 / 이벤트</h3>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setFormPrefill({});
                      setFormOpen(true);
                    }}
                  >
                    <Plus className="size-3.5" /> 추가
                  </Button>
                </div>
                <div className="space-y-2">
                  {events.length === 0 && <p className="text-sm text-muted-foreground">등록된 이벤트가 없습니다.</p>}
                  {events.map((e) => (
                    <div key={e.id} className="rounded-md border p-2.5 text-sm">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <Badge variant="outline">{eventTypeLabel(e.eventType)}</Badge>
                          {e.quantity !== null && <span className="text-xs text-muted-foreground">{formatSigned(e.quantity)}개</span>}
                        </div>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          {formatKstDateTime(e.eventDate)}
                          <button
                            onClick={() => handleDeleteEvent(e.id)}
                            className="rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-destructive/10 hover:text-destructive focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                            aria-label="삭제"
                          >
                            <Trash2 className="size-3.5" />
                          </button>
                        </div>
                      </div>
                      <p className="mt-1 text-sm">{e.note}</p>
                      <p className="mt-1 text-[11px] text-muted-foreground">작성자: {e.createdBy.name}</p>
                    </div>
                  ))}
                </div>
              </section>
            </div>

            <EventFormDialog
              open={formOpen}
              onOpenChange={setFormOpen}
              warehouseId={detail.descriptor.warehouseId}
              skuId={detail.descriptor.skuId}
              skuLabel={detail.descriptor.productName}
              defaultQuantity={formPrefill.quantity}
              defaultEventDate={formPrefill.date}
              onCreated={reload}
            />
          </>
        )}
      </SheetContent>
    </Sheet>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="font-medium tabular-nums">{value}</div>
    </div>
  );
}

function MetricCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border bg-card p-3">
      <div className="text-[11px] text-muted-foreground">{label}</div>
      <div className="mt-1 text-base font-semibold tracking-tight tabular-nums">{value}</div>
    </div>
  );
}

function fmtRate(value: number | null): string {
  return value === null ? '데이터 축적 중' : `${formatNumber(value)}개/일`;
}

function accelerationText(analysis: SkuAnalysis): string {
  const { trend, accelerationRatePercent } = analysis.acceleration;
  if (trend === null) return '데이터 축적 중';
  if (trend === 'NEW_DEPLETION') return '신규 소진 발생';
  if (trend === 'ACCELERATING') return `🔥 소진 가속 (+${Math.round(accelerationRatePercent ?? 0)}%)`;
  if (trend === 'DECELERATING') return `↓ 소진 둔화 (${Math.round(accelerationRatePercent ?? 0)}%)`;
  return '안정적';
}

function confidenceLabel(confidence: SkuAnalysis['forecast']['confidence']): string {
  if (confidence === 'HIGH') return '높음';
  if (confidence === 'MEDIUM') return '보통';
  if (confidence === 'LOW') return '낮음';
  return '-';
}

function thresholdSourceLabel(source: SkuAnalysis['riskThresholds']['source']): string {
  if (source === 'manual') return '관리자가 직접 설정한 값입니다.';
  if (source === 'legacy') return '업로드 파일이 제공한 값입니다.';
  if (source === 'auto') return '최소 7일이 관측된 구간의 추정 소진 속도로 자동 계산된 값입니다.';
  return '소진 이력이 부족해 위험 판정을 할 수 없습니다(데이터 축적 중).';
}
