import { prisma } from '@/lib/prisma';
import type { EventType } from '@prisma/client';

export interface CreateEventInput {
  warehouseId: string;
  skuId: string | null;
  eventType: EventType;
  quantity: number | null;
  note: string;
  eventDate: Date;
  isAutoGenerated?: boolean;
  createdById: string;
}

export function createEvent(input: CreateEventInput) {
  return prisma.inventoryEvent.create({ data: input });
}

export function listEventsForSku(skuId: string) {
  return prisma.inventoryEvent.findMany({
    where: { skuId, isDeleted: false },
    orderBy: { eventDate: 'desc' },
    include: { createdBy: { select: { name: true } } },
  });
}

export function listAllEvents(limit = 2000) {
  return prisma.inventoryEvent.findMany({
    where: { isDeleted: false },
    orderBy: { eventDate: 'desc' },
    take: limit,
    include: {
      createdBy: { select: { name: true } },
      warehouse: { select: { name: true } },
      sku: { select: { currentProductName: true } },
    },
  });
}

export function listEventsForWarehouse(warehouseId: string, limit = 50) {
  return prisma.inventoryEvent.findMany({
    where: { warehouseId, isDeleted: false },
    orderBy: { eventDate: 'desc' },
    take: limit,
    include: { createdBy: { select: { name: true } }, sku: { select: { currentProductName: true, productCode: true } } },
  });
}

export async function updateEvent(
  id: string,
  changedById: string,
  patch: { eventType?: EventType; quantity?: number | null; note?: string; eventDate?: Date },
) {
  return prisma.$transaction(async (tx) => {
    // FOR UPDATE로 행을 잠가, 동시에 같은 이벤트를 수정하는 두 요청이 같은 "수정 전" 값으로
    // 감사이력(EventHistory)을 중복 기록하지 않도록 한다 (두 번째 요청은 첫 번째가 커밋된 뒤의
    // 최신 값을 previousData로 읽게 된다).
    await tx.$executeRaw`SELECT id FROM inventory_events WHERE id = ${id} FOR UPDATE`;
    const existing = await tx.inventoryEvent.findUniqueOrThrow({ where: { id } });
    await tx.eventHistory.create({
      data: {
        eventId: id,
        changeType: 'UPDATE',
        previousData: {
          eventType: existing.eventType,
          quantity: existing.quantity,
          note: existing.note,
          eventDate: existing.eventDate.toISOString(),
        },
        changedById,
      },
    });
    return tx.inventoryEvent.update({ where: { id }, data: patch });
  });
}

export async function softDeleteEvent(id: string, changedById: string) {
  return prisma.$transaction(async (tx) => {
    await tx.$executeRaw`SELECT id FROM inventory_events WHERE id = ${id} FOR UPDATE`;
    const existing = await tx.inventoryEvent.findUniqueOrThrow({ where: { id } });
    await tx.eventHistory.create({
      data: {
        eventId: id,
        changeType: 'DELETE',
        previousData: {
          eventType: existing.eventType,
          quantity: existing.quantity,
          note: existing.note,
          eventDate: existing.eventDate.toISOString(),
          isDeleted: existing.isDeleted,
        },
        changedById,
      },
    });
    return tx.inventoryEvent.update({ where: { id }, data: { isDeleted: true } });
  });
}
