import { prisma } from '@/lib/prisma';
import type { EventType, Prisma } from '@prisma/client';
import { dateOnlyToString, formatKstDate } from '@/lib/date';
import { defaultScheduleColorFor } from '@/lib/schedule-colors';
import { areTitlesSimilar } from '@/domain/events/title-similarity';

type Db = typeof prisma | Prisma.TransactionClient;

export interface CreateEventInput {
  warehouseId: string;
  skuId: string | null;
  eventType: EventType;
  quantity: number | null;
  note: string;
  eventDate: Date;
  /** 기간 선택 시 종료일. 단일 날짜면 null(=eventDate와 같은 날). */
  endDate?: Date | null;
  /** 입력하면 같은 제목·기간·유형의 다른 SKU 이벤트와 캘린더 일정으로 묶인다. */
  title?: string | null;
  isAutoGenerated?: boolean;
  createdById: string;
  /** 유사 일정 확인 후 사용자가 "기존 일정에 추가"를 선택했을 때, 그 일정으로 강제 연결한다
   *  (이때 이 이벤트의 title도 그 일정의 제목으로 맞춘다 — "같은 제목으로 인식"). */
  attachToScheduleId?: string;
}

function toDateOnly(dateStr: string): Date {
  return new Date(`${dateStr}T00:00:00.000Z`);
}

function rangeDateOnly(eventDate: Date, endDate: Date | null | undefined) {
  const startDate = toDateOnly(formatKstDate(eventDate));
  return { startDate, endDate: endDate ? toDateOnly(formatKstDate(endDate)) : startDate };
}

export interface SimilarScheduleCandidate {
  scheduleId: string;
  title: string;
  startDate: string;
  endDate: string;
}

/**
 * 같은 유형·같은 기간(일자까지 정확히 동일)인데 제목만 "유사한"(완전히 같지는 않은) 기존 일정을
 * 찾는다. 완전히 같은 제목은 createEvent/updateEvent에서 자동으로 병합되므로 여기서는 후보에서
 * 제외한다 — 이건 어디까지나 "제목이 조금 다른데 같은 사안 같아 보이는" 경우 사용자에게 물어보기
 * 위한 것.
 */
export async function findSimilarSchedule(
  eventType: EventType,
  title: string,
  eventDate: Date,
  endDate: Date | null | undefined,
): Promise<SimilarScheduleCandidate | null> {
  const trimmedTitle = title.trim();
  const { startDate, endDate: endDateOnly } = rangeDateOnly(eventDate, endDate);
  const candidates = await prisma.eventSchedule.findMany({
    where: { eventType, startDate, endDate: endDateOnly, NOT: { title: trimmedTitle } },
  });
  const match = candidates.find((c) => areTitlesSimilar(c.title, trimmedTitle));
  if (!match) return null;
  return {
    scheduleId: match.id,
    title: match.title,
    startDate: dateOnlyToString(match.startDate),
    endDate: dateOnlyToString(match.endDate),
  };
}

/**
 * title이 있으면 (유형·제목·시작일·종료일)이 정확히 같은 기존 EventSchedule을 찾아 재사용하고,
 * 없으면 새로 만든다 — 서로 다른 SKU가 같은 이름·기간으로 이벤트를 등록해도 캘린더에는 하나의
 * 일정으로 합쳐 보이게 하기 위함. 이미 있던 일정이면 사용자가 지정해둔 색상을 그대로 유지한다.
 * attachToScheduleId가 오면(유사 일정 확인 후 사용자가 승인한 경우) 그 일정을 그대로 쓰고,
 * title도 그 일정의 제목으로 맞춘다. 제목이 없으면 일정 연결을 하지 않는다(수정 시 제목을
 * 지우면 연결도 함께 해제됨).
 */
async function resolveScheduleLink(
  db: Db,
  params: { eventType: EventType; title: string | null | undefined; eventDate: Date; endDate: Date | null | undefined; attachToScheduleId?: string },
): Promise<{ scheduleId: string | null; resolvedTitle: string | null }> {
  const trimmedTitle = params.title?.trim() || null;

  if (params.attachToScheduleId) {
    const schedule = await db.eventSchedule.findUnique({ where: { id: params.attachToScheduleId } });
    if (schedule) return { scheduleId: schedule.id, resolvedTitle: schedule.title };
  }

  if (trimmedTitle) {
    const { startDate, endDate } = rangeDateOnly(params.eventDate, params.endDate);
    const schedule = await db.eventSchedule.upsert({
      where: { eventType_title_startDate_endDate: { eventType: params.eventType, title: trimmedTitle, startDate, endDate } },
      create: { eventType: params.eventType, title: trimmedTitle, startDate, endDate, color: defaultScheduleColorFor(trimmedTitle) },
      update: {},
    });
    return { scheduleId: schedule.id, resolvedTitle: trimmedTitle };
  }

  return { scheduleId: null, resolvedTitle: null };
}

export async function createEvent(input: CreateEventInput) {
  const { scheduleId, resolvedTitle } = await resolveScheduleLink(prisma, {
    eventType: input.eventType,
    title: input.title,
    eventDate: input.eventDate,
    endDate: input.endDate,
    attachToScheduleId: input.attachToScheduleId,
  });

  return prisma.inventoryEvent.create({
    data: {
      warehouseId: input.warehouseId,
      skuId: input.skuId,
      eventType: input.eventType,
      quantity: input.quantity,
      note: input.note,
      eventDate: input.eventDate,
      endDate: input.endDate ?? null,
      title: resolvedTitle,
      scheduleId,
      isAutoGenerated: input.isAutoGenerated,
      createdById: input.createdById,
    },
  });
}

export function listEventsForSku(skuId: string) {
  return prisma.inventoryEvent.findMany({
    where: { skuId, isDeleted: false, sku: { is: { isActive: true } } },
    orderBy: { eventDate: 'desc' },
    include: { createdBy: { select: { name: true } } },
  });
}

export function listAllEvents(limit = 2000) {
  return prisma.inventoryEvent.findMany({
    where: { isDeleted: false, OR: [{ skuId: null }, { sku: { is: { isActive: true } } }] },
    orderBy: { eventDate: 'desc' },
    take: limit,
    include: {
      createdBy: { select: { name: true } },
      warehouse: { select: { name: true } },
      sku: { select: { currentProductName: true } },
    },
  });
}

export function listEventsForWarehouse(warehouseId: string, limit = 50) {
  return prisma.inventoryEvent.findMany({
    where: { warehouseId, isDeleted: false, OR: [{ skuId: null }, { sku: { is: { isActive: true } } }] },
    orderBy: { eventDate: 'desc' },
    take: limit,
    include: { createdBy: { select: { name: true } }, sku: { select: { currentProductName: true, productCode: true } } },
  });
}

export interface UpdateEventPatch {
  eventType: EventType;
  quantity: number | null;
  note: string;
  eventDate: Date;
  endDate?: Date | null;
  title?: string | null;
  attachToScheduleId?: string;
}

export async function updateEvent(id: string, changedById: string, patch: UpdateEventPatch) {
  return prisma.$transaction(async (tx) => {
    // FOR UPDATE로 행을 잠가, 동시에 같은 이벤트를 수정하는 두 요청이 같은 "수정 전" 값으로
    // 감사이력(EventHistory)을 중복 기록하지 않도록 한다 (두 번째 요청은 첫 번째가 커밋된 뒤의
    // 최신 값을 previousData로 읽게 된다).
    await tx.$executeRaw`SELECT id FROM inventory_events WHERE id = ${id} FOR UPDATE`;
    const existing = await tx.inventoryEvent.findUniqueOrThrow({ where: { id } });
    await tx.eventHistory.create({
      data: {
        eventId: id,
        changeType: 'UPDATE',
        previousData: {
          eventType: existing.eventType,
          quantity: existing.quantity,
          note: existing.note,
          eventDate: existing.eventDate.toISOString(),
          endDate: existing.endDate ? existing.endDate.toISOString() : null,
          title: existing.title,
        },
        changedById,
      },
    });

    const { scheduleId, resolvedTitle } = await resolveScheduleLink(tx, {
      eventType: patch.eventType,
      title: patch.title,
      eventDate: patch.eventDate,
      endDate: patch.endDate,
      attachToScheduleId: patch.attachToScheduleId,
    });

    return tx.inventoryEvent.update({
      where: { id },
      data: {
        eventType: patch.eventType,
        quantity: patch.quantity,
        note: patch.note,
        eventDate: patch.eventDate,
        endDate: patch.endDate ?? null,
        title: resolvedTitle,
        scheduleId,
      },
    });
  });
}

export async function softDeleteEvent(id: string, changedById: string) {
  return prisma.$transaction(async (tx) => {
    await tx.$executeRaw`SELECT id FROM inventory_events WHERE id = ${id} FOR UPDATE`;
    const existing = await tx.inventoryEvent.findUniqueOrThrow({ where: { id } });
    await tx.eventHistory.create({
      data: {
        eventId: id,
        changeType: 'DELETE',
        previousData: {
          eventType: existing.eventType,
          quantity: existing.quantity,
          note: existing.note,
          eventDate: existing.eventDate.toISOString(),
          isDeleted: existing.isDeleted,
        },
        changedById,
      },
    });
    return tx.inventoryEvent.update({ where: { id }, data: { isDeleted: true } });
  });
}
